spring.application.name=backend

# MongoDB
# Quick CRUD testing: embedded Mongo (Flapdoodle) will be used automatically.
# Later, switch to real MongoDB by setting env:
#   SPRING_DATA_MONGODB_URI=mongodb://localhost:27017/WebTech20252
spring.data.mongodb.database=WebTech20252
